groups:
- name: alert_rules
  interval: 1m
  rules:
  - alert: HighMemoryUsageApp1
    expr: |
      avg by (name) (
        container_memory_usage_bytes{name="docker1-app1-1"} / container_spec_memory_limit_bytes{name="docker1-app1-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker2-app1-1"} / container_spec_memory_limit_bytes{name="docker2-app1-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker3-app1-1"} / container_spec_memory_limit_bytes{name="docker3-app1-1"}
      ) > 0.75
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected on container {{ $labels.name }}"
      description: "Memory usage is over 75% for more than 1 minute."

  - alert: HighMemoryUsageApp2
    expr: |
      avg by (name) (
        container_memory_usage_bytes{name="docker1-app2-1"} / container_spec_memory_limit_bytes{name="docker1-app2-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker2-app2-1"} / container_spec_memory_limit_bytes{name="docker2-app2-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker3-app2-1"} / container_spec_memory_limit_bytes{name="docker3-app2-1"}
      ) > 0.75
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected on container {{ $labels.name }}"
      description: "Memory usage is over 75% for more than 1 minute."

  - alert: HighMemoryUsageApp3
    expr: |
      avg by (name) (
        container_memory_usage_bytes{name="docker1-app3-1"} / container_spec_memory_limit_bytes{name="docker1-app3-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker2-app3-1"} / container_spec_memory_limit_bytes{name="docker2-app3-1"}
      ) > 0.75
      or
      avg by (name) (
        container_memory_usage_bytes{name="docker3-app3-1"} / container_spec_memory_limit_bytes{name="docker3-app3-1"}
      ) > 0.75
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected on container {{ $labels.name }}"
      description: "Memory usage is over 75% for more than 1 minute."

  - alert: HighCPUUsageApp1
    expr: |
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker1-app1-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker2-app1-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker3-app1-1"}[5m])
      ) > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on container {{ $labels.name }}"
      description: "CPU usage is over 80% for more than 1 minuto."

  - alert: HighCPUUsageApp2
    expr: |
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker1-app2-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker2-app2-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker3-app2-1"}[5m])
      ) > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on container {{ $labels.name }}"
      description: "CPU usage is over 80% for more than 1 minuto."

  - alert: HighCPUUsageApp3
    expr: |
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker1-app3-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker2-app3-1"}[5m])
      ) > 0.8
      or
      avg by (name) (
        rate(container_cpu_usage_seconds_total{name="docker3-app3-1"}[5m])
      ) > 0.8
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on container {{ $labels.name }}"
      description: "CPU usage is over 80% for more than 1 minuto."
  - alert: ContainerDownApp1
    expr: |
      absent(container_memory_usage_bytes{name="docker1-app1-1"})
      or
      absent(container_memory_usage_bytes{name="docker2-app1-1"})
      or
      absent(container_memory_usage_bytes{name="docker3-app1-1"})
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.name }} is down"
      description: "No metrics detected for container {{ $labels.name }} for more than 1 minute."

  - alert: ContainerDownApp2
    expr: |
      absent(container_memory_usage_bytes{name="docker1-app2-1"})
      or
      absent(container_memory_usage_bytes{name="docker2-app2-1"})
      or
      absent(container_memory_usage_bytes{name="docker3-app2-1"})
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.name }} is down"
      description: "No metrics detected for container {{ $labels.name }} for more than 1 minute."

  - alert: ContainerDownApp3
    expr: |
      absent(container_memory_usage_bytes{name="docker1-app3-1"})
      or
      absent(container_memory_usage_bytes{name="docker2-app3-1"})
      or
      absent(container_memory_usage_bytes{name="docker3-app3-1"})
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.name }} is down"
      description: "No metrics detected for container {{ $labels.name }} for more than 1 minute."
