scrape_configs:
  - job_name: 's4-containers'
    static_configs:
      - targets: ['192.168.1.141:8080']
        labels:
          instance: 'docker1'
          engine: 'docker1'
      - targets: ['192.168.1.142:8080']
        labels:
          instance: 'docker2'
          engine: 'docker2'
      - targets: ['192.168.1.143:8080']
        labels:
          instance: 'docker3'
          engine: 'docker3'
