 groups:
  - name: UbuntuServersAlerts
    rules:
      - alert: HighCPUDifference
        expr: |
          (
            (rate(node_cpu_seconds_total{mode="idle"}[1m]) by (instance))
            - ignoring(instance)
            group_left
            (rate(node_cpu_seconds_total{mode="idle"}[1m]) by (instance))
          )
          / ignoring(instance)
          group_left
          (rate(node_cpu_seconds_total{mode="idle"}[1m]) by (instance))
          > 0.2
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage difference detected"
          description: |
            The CPU usage of instance {{ $labels.instance }} is significantly different from other instances.

      - alert: HighRAMDifference
        expr: |
          (
            (node_memory_Active_bytes by (instance))
            - ignoring(instance)
            group_left
            (node_memory_Active_bytes by (instance))
          )
          / ignoring(instance)
          group_left
          (node_memory_Active_bytes by (instance))
          > 0.2
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "High RAM usage difference detected"
          description: |
            The RAM usage of instance {{ $labels.instance }} is significantly different from other instances.

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "Instance {{ $labels.instance }} has been down for more than 1 minute."
